### ISSUE TITLE
Unable to clean shows with unicode characters in title

### ISSUE THREAD

**Issue by Anthirian** [Anthirian/script.filecleaner#48]
[Chubbs](http://forum.kodi.tv/showthread.php?tid=162517&pid=2303723#pid2303723): Cleaning shows with Russian Cyrillic characters in their titles results in a `UnicodeDecodeError`.

````
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.UnicodeDecodeError'>
Error Contents: 'utf8' codec can't decode byte 0xc1 in position 0: invalid start byte
Traceback (most recent call last):
	File "C:\..\script.filecleaner-master\service.py", line 47, in <module>autostart()
	File "C:\..\script.filecleaner-master\service.py", line 33, in autostart results, _ = cleaner.clean_all()
	File "C:\..\script.filecleaner-master\default.py", line 233, in clean_all cleaned_files, count, status = self.clean(video_type)
	File "C:\..\script.filecleaner-master\default.py", line 141, in clean expired_videos = self.get_expired_videos(video_type)
	File "C:\..\script.filecleaner-master\default.py", line 335, in get_expired_videos result = json.loads(response)
	File "C:..\Kodi\system\python\Lib\json\__init__.py", line 338, in loads return _default_decoder.decode(s)
	File "C:\..\Kodi\system\python\Lib\json\decoder.py", line 366, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end())
	File "C:\..\Kodi\system\python\Lib\json\decoder.py", line 382, in raw_decode obj, end = self.scan_once(s, idx)
	UnicodeDecodeError: 'utf8' codec can't decode byte 0xc1 in position 0: invalid start byte
	-->End of Python script error report<--

````

**Comment by Anthirian** [comment]
Fixed in d9fb909cb41cbfac3dcb2eb3c34224a3d3fc1fa3
